---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: players
  label: Players
  create: all
  match: "**/*"
- type: directory
  path: page
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: gridsome build
